// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskSchedular.Models;

#nullable disable

namespace wayPointLatest.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Money_Finder.Models.AdminLogin", b =>
                {
                    b.Property<int>("AdminLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminLoginId"), 1L, 1);

                    b.Property<string>("AccessCampaign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccessProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccessSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkypeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemRoll")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TryCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminLoginId");

                    b.ToTable("AdminLogin");
                });

            modelBuilder.Entity("TaskSchedular.Models.Campaigns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Labels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostponeDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rejectedtoday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asignedtoday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("auth_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("campaignname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("datetime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deliverymethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deliverythrottle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("esp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("espa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("espb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("espc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("espd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("espe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exclusivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leadperday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("list")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("list_id")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sourcename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("todayremaining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("totalasign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("totalleads")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("totalremaining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("validresponses")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("TaskSchedular.Models.forccgcosmolead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("auth_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("datecreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("forccgcosmolead");
                });

            modelBuilder.Entity("TaskSchedular.Models.provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("auth_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("provider");
                });

            modelBuilder.Entity("TaskSchedular.Models.sendoncosmolead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("auth_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("datecreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("sendoncosmolead");
                });

            modelBuilder.Entity("TaskSchedular.Models.source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asignto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("auth_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("datecreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dupcount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dupcounttoday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dupe_check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sourcecompanyname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("totalleads")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("source");
                });

            modelBuilder.Entity("TaskSchedular.Models.sourcelead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("added_source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("archieve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asignto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("auth_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("datecreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("esp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("group_id")
                        .HasColumnType("int");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("list")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lu_carrier_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lu_carrier_error_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lu_carrier_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lu_international_format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lu_local_format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("optin_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("source_id")
                        .HasColumnType("int");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timezone_dst_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updated_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.Property<string>("zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("sourcelead");
                });

            modelBuilder.Entity("TaskSchedular.Models.sourcelist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("campaignname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("list")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sourcename")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("sourcelist");
                });
#pragma warning restore 612, 618
        }
    }
}
